volumes:
  frontend:
  database:
  pnpm_store:
services:



  # --------------------
  # Dev
  # --------------------

  dev:
    build:
      context: .
      target: base
      args:
        WORK_DIR: ${WORK_DIR}
        PNPM_DIR: ${PNPM_DIR}
    tty: true
    environment:
      NODE_ENV: development
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
      - 3000:3000 # analyze
    volumes:
      - pnpm_store:${PNPM_DIR}
      - ./:/app
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy



  # --------------------
  # Prod
  # --------------------

  prod:
    build:
      context: .
      target: prod
      args:
        WORK_DIR: ${WORK_DIR}
        PNPM_DIR: ${PNPM_DIR}
    environment:
      NODE_ENV: production
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - pnpm_store:${PNPM_DIR}
      - ./packages/directus/uploads:/app/packages/directus/uploads
      - ./packages/website/dist:/app/packages/website/dist
    env_file:
      - .env
    depends_on:
      caddy:
        condition: service_started
      database:
        condition: service_healthy



  # --------------------
  # Caddy
  # --------------------

  caddy:
    image: caddy:2-alpine
    ports:
      - ${CADDY_PORT}:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./packages/website/dist:/www



  # --------------------
  # Database
  # --------------------

  database:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    command: postgres -p ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE} -p ${DB_PORT}" ]
      interval: 5s
      timeout: 5s
      retries: 5
