export { default as LFooter } from '~/layout/l-footer.vue'
export { default as LHeader } from '~/layout/l-header.vue'
export { default as LHero } from '~/layout/l-hero.vue'
export { default as LSection } from '~/layout/l-section.vue'

export { default as ItemBlog } from '~/items/item-blog.vue'
export { default as ItemHow } from '~/items/item-how.vue'
export { default as ItemWhat } from '~/items/item-what.vue'
export { default as ItemWhy } from '~/items/item-why.vue'

export { default as UiSlider } from '~/ui/ui-slider.vue'
export { default as UiButton } from '~/ui/ui-button.vue'

export { default as IcLogo } from '~/icons/ic-logo.svg'
export { default as IcLeft } from '~/icons/ic-left.svg'
export { default as IcRight } from '~/icons/ic-right.svg'
export { default as IcPhone } from '~/icons/ic-phone.svg'
export { default as IcMail } from '~/icons/ic-mail.svg'
export { default as IcWhat } from '~/icons/ic-what.svg'
export { default as IcFacebook } from '~/icons/ic-facebook.svg'
export { default as IcInstagram } from '~/icons/ic-instagram.svg'
export { default as IcLinkedin } from '~/icons/ic-linkedin.svg'
export { default as IcTwitter } from '~/icons/ic-twitter.svg'
export { default as IcMenu } from '~/icons/ic-menu.svg'