const {
    DIRECTUS_PORT,
    DIRECTUS_URL,
    DIRECTUS_KEY,
    DIRECTUS_SECRET,
} = process.env

module.exports = {
    KEY: DIRECTUS_KEY,
    SECRET: DIRECTUS_SECRET,
    DB_CLIENT: 'pg',
    PORT: DIRECTUS_PORT,
    PUBLIC_URL: DIRECTUS_URL,
    REDIS_ENABLED: false
}